### ISSUE TITLE
How to change base_url of resources

### ISSUE THREAD

**Issue by ivanoterouvigo** [campusdomar/PuMuKIT2#1]
Hi all!

I cloned this repository in localhost. When I try to see one video this tells that isn´t video.
When I check src of <video ></video> I see that it has a relative url. If I insert base_url in browse edition it work fine. Where I have to change or add this base_url?

Thank you

**Comment by mreyk** [comment]
Hi,

The video url must be relative. Couldn't you watch the video at frontend or backend? Could you explain better your issue?

**Comment by mreyk** [comment]
Have you solved this issue?

**Comment by mreyk** [comment]
Close do to inactivity.
