### ISSUE TITLE
on /admin/series/ page, internal error when clicking "New" button

### ISSUE THREAD

**Issue by fishfree** [campusdomar/PuMuKIT2#118]
The error tip shows in the left down corenr of the page: Internal Server Error: error, An Error Occurred: Internal Server Error
tail /var/log/nginx/pumukit2_error.log
2016/05/10 08:22:15 [error] 20937#0: *43 FastCGI sent in stderr: "2/app/bootstrap.php.cache:2987
PHP message: PHP  11. Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch() /var/www/pumukit2/app/bootstrap.php.cache:3014
PHP message: PHP  12. Symfony\Component\EventDispatcher\EventDispatcher->dispatch() /var/www/pumukit2/app/cache/prod/classes.php:2299
PHP message: PHP  13. Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() /var/www/pumukit2/app/cache/prod/classes.php:2138
PHP message: PHP  14. call_user_func() /var/www/pumukit2/app/cache/prod/classes.php:2205
PHP message: PHP  15. Pumukit\SchemaBundle\EventListener\LocaleListener->onKernelRequest() /var/www/pumukit2/app/cache/prod/classes.php:2205
PHP message: PHP  16. in_array() /var/www/pumukit2/src/Pumukit/SchemaBundle/EventListener/LocaleListener.php:44" while reading response header from upstream, client: 10.2.8.19, server: videoportal.dev, request: "GET /admin/series/create HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "videoportal.dev", referrer: "http://videoportal.dev/admin/series/"

**Comment by Alfro** [comment]
It seems like it can be related to the #119 issue you opened. Please try to solve it first and then come back to this issue if it still happens to you.
