### ISSUE TITLE
#6695 Installation Guide: Add complete user creation

### ISSUE THREAD

**Issue by bmartinezteltek** [campusdomar/PuMuKIT2#12]
After create the user it must be activated.

php app/console fos:user:activate

**Comment by mercefan** [comment]
During the installation process of the [Installation Guide](https://github.com/campusdomar/PuMuKIT2/blob/master/doc/InstallationGuide.md) it is enough to execute:

```
php app/console fos:user:create admin --super-admin
```

to create the `admin` user activated.

Try again from scratch.

**Comment by mreyk** [comment]
During the installation process of the [Installation Guide](https://github.com/campusdomar/PuMuKIT2/blob/master/doc/InstallationGuide.md) it is enough to execute:

```
php app/console fos:user:create admin --super-admin
```

to create the `admin` user activated.

Try again from scratch.

**Comment by bmartinezteltek** [comment]
Tested OK.
