### ISSUE TITLE
#6694 Installation Guide: Tag 2.0.0 not updated

### ISSUE THREAD

**Issue by bmartinezteltek** [campusdomar/PuMuKIT2#13]
Installation guide from pumukit.org tells to choose the tag 2.0.0 (git checkout 2.0.0) which is a pumukit2 version not updated.

**Comment by mreyk** [comment]
Already change at http://pumukit.org/documentation-pmk-2-x/

**Comment by bmartinezteltek** [comment]
Tested OK.
