### ISSUE TITLE
#6692 Installation Guide:  Prepare environment : localhost:27017: norepl: no replication has been enabled

### ISSUE THREAD

**Issue by bmartinezteltek** [campusdomar/PuMuKIT2#14]
Message:

root@vagrant:/var/www/pumukit2# php app/console doctrine:mongodb:schema:create
Created dbs for all classes
Created collections for all classes
localhost:27017: norepl: no replication has been enabled, so w="true" won't work

Configure: 
 app/config/parameters.yml (mongoDB)

**Comment by Alfro** [comment]
This is due to an unusual configuration of your mongoDB.
It is better to follow the installations steps at the [PuMuKIT2 Installation Guide](https://github.com/campusdomar/PuMuKIT2-doc/blob/master/InstallationGuide.md#pumukit-2-installation-guide)
