### ISSUE TITLE
Moodle playlist: the name is incorrect in the pumukit menu

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT2#140]
Steps:
- Enter in the pumukit backoffice
- Select playlist in the pumukit menu bar (inside mediamanager option)

Problem: The name in the menu bar is playlist but it must be Moodle playlist.

**Comment by Alfro** [comment]
@silviabf Test again.

**Comment by shermida** [comment]
The name in the menu bar is Moodle Playlist. The issue has been fixed.
