### ISSUE TITLE
Moodle playlist: It is shown Cancel search in playlist page when you do a search in a series

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT2#142]
Steps:
- Enter in pumukit backoffice
- Do a search in series page
- Go to playlist page

Problem:
In the playlist page you can see "Cancel search" when you are not doing any search in this page. If you click in "cancel search" does not happen anything. If you want to dissapear "cancel search" you have to return to series page and then cancel search there.

**Edit:** Added image
![cancel_search](https://cloud.githubusercontent.com/assets/11334172/16297260/600c3918-3930-11e6-875e-a671c7adfb59.png)

**Comment by Alfro** [comment]
@silviabf Please add at least an image next time. It makes the issue way more understandable.

**Comment by Alfro** [comment]
@silviabf Test again.

**Comment by shermida** [comment]
The issue has been fixed.
