### ISSUE TITLE
Moodle playlist: the search option does not search correctly in all cases

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT2#143]
Steps:
- Enter backoffice and go to playlist page
- Search "new"
- Reset search
- Search a word that is only in one title of a playlist

Problem:
When you search by "new", the order of the playlists changes but all the playlists are shown (i do not where is searching because not all the playlist have "new" in its title. In the second search, the search is ok, but there is no option cancel search under the playlists.

**Comment by Alfro** [comment]
@silviabf These are two different issues. 
* To the first issue: (Now #164) It also happens with Series.
* To the second issue: (Now #165) Should be fixed with #142 (74c454e).

I am closing this issue.
