### ISSUE TITLE
Thumbnail: when add the first new thumbnail in a series or playlist, list a page that does not exist

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT2#144]
Steps:
- Enter in the pumukit backoffice
- Create a new series
- Go to thumbnails and click New thumbnail

Problem:
As you can see in the attached picture, in the use thumbnail section there is two pages (1,0) when only one page exists.
![thumbnail](https://cloud.githubusercontent.com/assets/11191010/16197041/c0f7aa50-3700-11e6-8a9a-af1788ab5d6a.png)

**Comment by shermida** [comment]
The issue has been solved.
