### ISSUE TITLE
Moodle playlist: there is no name in the window add to a playlist when create a new playlist

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT2#145]
Steps:
- Enter in pumukit backoffice
- Click on any series (with videos)
- Select a video and click on hamburguer icon or in the "select an action" pull-down menu
- Select Add to a playlist
- Click on "Create new playlist" and write a title
- Click on "Create playlist"

Problem:
The new playlist is created but in the list of playlist to select there is no title as you can see in the attached picture
![sin titulo](https://cloud.githubusercontent.com/assets/11191010/16198013/910fa064-3704-11e6-93ec-e9ceaac7a242.png)

**Comment by Alfro** [comment]
@silviabf Test again.

**Comment by shermida** [comment]
The new playlist created has title. The issue has been fixed.
