### ISSUE TITLE
Moodle playlist: You can not add various videos to a playlist at once

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT2#146]
Steps:
- Enter in the pumukit backoffice
- Select a series with various videos
- Mark the checkbox of two or three published videos
- Click on pull-down menu "Select an action" and select "Add to playlist"
- Select any playlist and Add

Problem: The videos does not added to the selected playlist.

**Comment by Alfro** [comment]
@silviabf Test again.

**Comment by shermida** [comment]
It is possible to add more than one video at the same time to a playlist. Therefore, the issue has been fixed.
