### ISSUE TITLE
Moodle playlist: You can not delete the thumbnails

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT2#147]
Steps:
- Enter in the pumukit backoffice
- enter in the playlist section
- Select any playlist and upload a thumbnail
- Click the x icon under the thumbnail to delete it

Problem: The thumbnail is not deleted

**Comment by Alfro** [comment]
@silviabf It should be fixed now.

**Comment by shermida** [comment]
Thumbnails can be deleted. The issue has been fixed.
