### ISSUE TITLE
Moodle playlist: add a video to a playlist from options of a multimedia object overwrites the first video of the playlist

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT2#148]
Steps:
- Enter in pumukit backoffice and select playlist
- Create a new playlist and add two differents videos from "my videos"
- Go to series and select any series
- Select any video and click on option button (hamburger icon)
- Select "Add to playlist" and add the video to the previously created playlist
- Go to the playlist

Problem: This video is always added as the first video of the playlist, and if the playlist is not empty, this video overwrite the first video of the playlist.

**Comment by Alfro** [comment]
@silviabf Take a look at this again. It should be fixed with yesterday's update

**Comment by silviabf** [comment]
Fixed with yesterday's update. The video is added correctly to the playlist now. I close this issue.
