### ISSUE TITLE
Moodle playlist: you can not add videos as auto publisher in any way from inside a playlist.

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT2#153]
Steps:
- Enter in pumukit backoffice as a autopublisher
- Go to playlist section
- Create a new playlist
- Enter in the playlist and click on add
- Try to add videos with search, url or my videos

Problem: If you try to add videos with search or url, you write anything and you have not response only white in the window (for correct or incorrect data). If you try to add videos with my videos, you can see and select the correct videos (videos that you upload only) but when you click on add, the videos are not added to the playlist.

**Comment by Alfro** [comment]
@silviabf Try it again after the update.

**Comment by silviabf** [comment]
I can add videos with an autopublisher user in the three ways now. I close this issue.
