### ISSUE TITLE
Moodle playlist: Error 500 if a admin adds a video in a playlist of a autopublisher

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT2#154]
Steps:
- Enter in pumukit backoffice as autopublisher
- Create a playlist and add a video
- Log off and enter in pumukit backoffice as admin
- Enter in the previous playlist and add a video that autopublisher does not own
- Log off and enter again with the autopublisher account
- Enter in the playlist

Problem: you have a 500 error:
```
Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```
when you try to enter, because you can not see the video that admin add to the playlist

**Comment by Alfro** [comment]
@silviabf This should be fixed as well with yesterday's commits. Take a look again, please.

**Comment by shermida** [comment]
It is possible to add a video without error.
