### ISSUE TITLE
Moodle playlist: you can add videos to a playlist with a incorrect url

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT2#155]
Steps:
- Enter in pumukit backoffice
- Copy the url of a video
- Go to playlist and create a new playlist
- Enter in the playlist and click add
- Select url option and paste the previous url
- Modify the url without change the format and the video id, for example: https://example.domain.org/video/575e76d87d1c531c438b456e

Problem: The video is added to the playlist because the format of url and the id are correct. I doubt if it is a bug or not? (If you write a url that does not have the correct format or id, it works correctly and it does not add the video)

**Comment by rubenrua** [comment]
At this moment, no bug.
