### ISSUE TITLE
Moodle playlist: private videos are played in a playlist without ask password

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT2#157]
Steps:
- Enter in pumukit backoffice
- Enter in playlist section
- Create a new playlist
- Add to a playlist a public video, a video protected by password, a video that only can see the members of a group and a video that only can see logged users
- Play the playlist (by preview url) in a browser without login in pumukit

Problem: Without login in pumukit, the playlist play all the videos without asking by a password. It only have to play the public video.

**Comment by Alfro** [comment]
35a130077b6fd33fc8c2ff4015535cbe6a3dfc87

**Comment by Alfro** [comment]
@silviabf Try it again.

**Comment by shermida** [comment]
I have created a new playlist with 4 MO with different broadcast profiles. I can see all videos with the preview url. I do not need to log in with a valid user or enter a password.

**Comment by shermida** [comment]
Only videos with public broadcast can be viewed in the playlist preview. Although, it is confusing do not be able to see (in the preview) videos with another broadcast profile, even if the user is allow to or has the password to see it.

**Comment by Alfro** [comment]
@shermida We will add a warning to clarify which objects will be played.
Take a look at #187
