### ISSUE TITLE
Moodle playlist: Pumukit asks password to add by using url in a playlist a protected by password video

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT2#158]
Steps:
- Enter in pumukit backoffice
- In one series, change the broadcast profile of a video to protected by password
- Copy the url of this video from info
- Go to playlist section
- In any playlist select add, and you add the video by url

Problem: When you copy the url, a pop up window is opened to ask the password of the video. If you click on cancel, as you can see in the attached picture, pumukit shows the series page instead the video preview. But, in any case, you can add the video to the playlist.
![urlvideoprivado](https://cloud.githubusercontent.com/assets/11191010/16264164/37bc319c-3878-11e6-84a0-210b749a16ca.png)

**Comment by Alfro** [comment]
After adding #175, this bug does not have as much priority.

**Comment by rubenrua** [comment]
@silviabf Could you check if the window asking for the password is popping up?

The form asking for the password may be inside the player.

**Comment by shermida** [comment]
The window asking for the password is popping up and the video can be reproduced if the correct password is entered.
![pass_popup](https://cloud.githubusercontent.com/assets/19668673/16725705/c464ecda-4758-11e6-839e-db1e6daa2722.png)
