### ISSUE TITLE
Moodle playlist: playlist breaks if you delete a multimedia object from the playlist in its series

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT2#159]
Steps:
- Enter in pumukit backoffice
- Add a video to a playlist
- go to series section and delete this video
- Return to playlist section and enter in the playlist

Problem: There is an error because a element of the playlist does not exists:
```
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. 
```

**Comment by Alfro** [comment]
@silviabf It should be fixed now. Give it a try.
(Note: If you already have a playlist from a previous test, that playlist will still be broken)

**Comment by shermida** [comment]
A multimedia object added to a Playlist can be deleted without breaking the Playlist. The issue has been fixed.
