### ISSUE TITLE
Moodle playlist: user administrator does not have by default permission:  Access Edit Playlist 

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT2#160]
Steps:
- Enter in pumukit backoffice
- Go to Permission Profiles

Problem: As you can see in the attached picture, users Administrator can not create playlist.
![admin](https://cloud.githubusercontent.com/assets/11191010/16266177/bd8cce02-3883-11e6-83ba-4d1e49a37110.png)

**Comment by Alfro** [comment]
The following command needs to be executed in order to update the environment:
`php app/console pumukit:permission:update Administrator ROLE_ACCESS_EDIT_PLAYLIST`

**Comment by Alfro** [comment]
@silviabf After the env is updated with that command, try it again. It should be solved.

**Comment by shermida** [comment]
Users Administrator can create playlist. The issue has been fixed.
