### ISSUE TITLE
Moodle playlist: A user with no Access to playlists can still see its Menu Option

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT2#161]
Steps:
- Enter in pumukit backoffice with a user that does not have "Access Edit Playlist" checked in its permission profiles
- Click on media manager
- Click on playlist

Problem: This user can see "playlist" but then he can not enter because he does not have permission. I think it is better that he can not see the option playlist

**Comment by Alfro** [comment]
@silviabf Test again.

**Comment by shermida** [comment]
A user with no access to playlist cannot see its Menu Option anymore. Therefore, the issue has been fixed.
