### ISSUE TITLE
Moodle playlist: user with scope_personal (autopublisher) can add to a playlist restricted videos by group videos (when he is not in this group)

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT2#162]
Steps:
- Enter in pumukit backoffice with a user admin
- Add a video and use as broadcast: only people of the group ... 
- Log off and enter again with a user autopublisher (that he is not in any group)
- Add in a playlist (by url or by search) the previous video

Problem: In the preview of the video, pumukit says that the access is restricted but autopublisher user can add the video to its playlist.

**Comment by Alfro** [comment]
**Added Screenshot:**
![captura](https://cloud.githubusercontent.com/assets/11334172/16577000/ee40952e-4292-11e6-9281-ab7dc33bd7db.png)

**Comment by Alfro** [comment]
Since the video is listed on the Video Portal, said video can be added to the playlist. However, an user viewing the playlists without rights to view the multimedia object will not see that video on the playlist.
@rubenrua Is this the correct behaviour as of now?

**Comment by rubenrua** [comment]
We don't deny adding restricted access videos to a moodle playlist. You also can add a public video and if the owner changes the brodcast of the video and you'll get a restricted access video in your  moodle playlist. The  restricted access video aren't listed in the playlist. 

With #188 we are adding a warning for non-playable videos to improve the UX.
