### ISSUE TITLE
Media Manager: The search options shows all Series/Playlists when searching 'new'

### ISSUE THREAD

**Issue by Alfro** [campusdomar/PuMuKIT2#164]
**Steps:**
* Search for the 'new' keyword on either the Series or the Playlists search.

**Result:**
* All series are shown, even those with **no objects or no apparent keywords with 'new'**.
![series_save](https://cloud.githubusercontent.com/assets/11334172/16299715/008b5396-393c-11e6-9169-f794144d89f6.png)

**Comment by Alfro** [comment]
@rubenrua The prototype objects were also being added to the search. I excluded them using createStandardQueryBuilder instead.

**Comment by shermida** [comment]
When searching for the "new" keyword, all series are shown, even those with multimedia objects with title "new". However, in playlist the behaviour is different, only the playlist with title "new" are shown, no matter if another playlist has multimedia objects with title "new".
