### ISSUE TITLE
Moodle Playlists: The 'cancel search' option does not appear

### ISSUE THREAD

**Issue by Alfro** [campusdomar/PuMuKIT2#165]
**Steps:**
* Search for any keyword on the Playlist search.

**Result:**
* There is no 'cancel search' option in the Playlists listing (unlike with the Series search.)

*On playlist:*
![playlist_search](https://cloud.githubusercontent.com/assets/11334172/16299809/7b099a74-393c-11e6-89f4-eaade21bc303.png)
*On series:*
![series_ss](https://cloud.githubusercontent.com/assets/11334172/16299864/da9469e2-393c-11e6-9195-34baa7464785.png)

**Comment by Alfro** [comment]
Should be fixed with #142 (74c454e).

**Comment by Alfro** [comment]
@silviabf Test again.

**Comment by shermida** [comment]
The issue has been fixed.
