### ISSUE TITLE
Moodle Playlist: Error 404 in Preview link if the Playlist is empty or with all the videos Hidden and/or Blocked

### ISSUE THREAD

**Issue by shermida** [campusdomar/PuMuKIT2#169]
**Steps:**

- Click in Media Manager >> Series

- Create a new Series with multimedia objects

- In the Publication tab of all the multimedia objects created, select Hidden or Blocked:

![publication tab](https://cloud.githubusercontent.com/assets/19668673/16410306/2f2aa578-3d22-11e6-8aeb-21cbc374017f.png)

- Add the multimedia objects to a new Playlist:

![add playlist](https://cloud.githubusercontent.com/assets/19668673/16410278/08cc495e-3d22-11e6-9fdf-3aad7046f156.png)

- Click in Media Manager >> Moodle Playlist

- Select the new Playlist created and click in Preview:

![preview_playlist](https://cloud.githubusercontent.com/assets/19668673/16410531/3735fe60-3d23-11e6-9612-2170530d86cd.png)

**Result:**

- Error "404 Not Found" in the Video Portal.

**Comment by Alfro** [comment]
The "Error 404" is not an unwanted behavior.
However, I added a custom screen that should be more user-friendly for when it happens. (Specially when embedding it somewhere)

**Comment by shermida** [comment]
The custom screen is better than the error 404.
