### ISSUE TITLE
Moodle Playlist: Some options in Select an Action menu do not work 

### ISSUE THREAD

**Issue by shermida** [campusdomar/PuMuKIT2#171]
**Steps:**

- Click in Media Manager >> Moodle Playlist.

- Click in _videos_ at any Playlist with multimedia objects.

- Click in the dropdown menu _Select an Action_ and select any option except _Delete Selected_:
![dropdown_menu](https://cloud.githubusercontent.com/assets/19668673/16412557/240bdf9e-3d2d-11e6-9a20-f0b407a482f5.png)

**Result:**

- Nothing happens. Mm. Obj. order do not change and there is no preview of the playlist.

**Comment by Alfro** [comment]
I removed the extra options. Those come from the Multimedia Object view, but are not implemented for playlists.

**Comment by shermida** [comment]
Those options have been removed so the issue has been solved.
