### ISSUE TITLE
Moodle Playlist: Search bug when searching with spaces

### ISSUE THREAD

**Issue by shermida** [campusdomar/PuMuKIT2#173]
**Steps:**

- Click in media Manager >> Moodle Playlist

- Select any Playlist

- Click in Add

- Click in Search
![search_add_playlist](https://cloud.githubusercontent.com/assets/19668673/16415877/c015e882-3d3f-11e6-8a67-ffd946775ece.png)

- Search the video with the title _Playlist Video 3_ typing in Search only _Playlist_ and then click in Search (**Result 1**)

- Search the video with the title _Playlist Video 3_ typing in Search  _Playlist Video_ and then click in Search (**Result 2**)

- Search the video with the title _Playlist Video 3_ typing in Search only _Playlist_ but with a white space at the end, then click in Search (Same result as the one explained in **Result 2**)

**Result 1:**

- All Mm. Obj. with the word _Playlist_ have been found. 
![search_one_word](https://cloud.githubusercontent.com/assets/19668673/16417422/11ab4ace-3d46-11e6-94be-d57c3f587f68.png)

**Result 2:**

- No Mm. Obj. with the words _Playlist Video_ have been found. 
![search_two_words](https://cloud.githubusercontent.com/assets/19668673/16417560/aa55f404-3d46-11e6-9a83-f32457453cfe.png)

**Comment by Alfro** [comment]
**Issue:** The search does not seem to search correctly when whitespace characters are involved.

**Comment by shermida** [comment]
The issue has been solved.
