### ISSUE TITLE
Moodle Playlist: Firefox: Playlist dropdown menu do not work 

### ISSUE THREAD

**Issue by shermida** [campusdomar/PuMuKIT2#177]
**Steps:**

- Open PuMuKIT in Firefox Web Browser

- Click in Media Manager >> Moodle Playlist

- Click in _videos_ at any Playlist

- Click in the dropdown menu _Select an action_ (bottom left)
![dropdown_menu](https://cloud.githubusercontent.com/assets/19668673/16450380/e267b178-3dfc-11e6-8240-6b394de4130b.png)

**Result:**

- Nothing happens. The dropdown menu do not show the options available.

**Comment by rubenrua** [comment]
Not reproducible.

**Comment by shermida** [comment]
@rubenrua I have tried again in Merchi's Firefox and it happened the same

**Comment by shermida** [comment]
The issue has been solved.
