### ISSUE TITLE
#6965 Frontend: Material's icons not shown

### ISSUE THREAD

**Issue by bmartinezteltek** [campusdomar/PuMuKIT2#18]
Material's icons not shown (pdf, ppt, doc...) nor the series visualization nor the video playing

**Comment by mreyk** [comment]
Fixed in commits 60dbc7b630c383890188ed100d9f93ba2ad2d5ec 7123c70fe3df0f47d030d01c4e2d88fd8cf1b868

**Comment by bmartinezteltek** [comment]
Tested OK.
