### ISSUE TITLE
Media Manager: Add warning to non-playable objects on a Playlist

### ISSUE THREAD

**Issue by Alfro** [campusdomar/PuMuKIT2#187]
Sometimes, a multimedia objects is added to a playlist with a Broadcast that prevents it from being played. This is not always obvious for the user.
* **Proposition:** Add warning to unplayable objects.
![proposition](https://cloud.githubusercontent.com/assets/11334172/16588274/b1553142-42ce-11e6-8db4-be8d394f5a86.png)

**Comment by Alfro** [comment]
Added simple icon.
@rubenrua Code review and to QA.

**Comment by Alfro** [comment]
@shermida Take a look at this.
Make sure it shows the warning on those cases where the video does not play.

**Comment by shermida** [comment]
The warning only appear if the video Broadcast profile is "Only logged in users". There is no warning if the broadcast is password protected or only users in groups.

**Comment by Alfro** [comment]
@shermida It should have been fixed already.

**Comment by shermida** [comment]
The warning do not show only if the video is public. The only problem now is that the warning mesage has two brackets at the end like this: "This object cannot be played on the playlist()".

**Comment by Alfro** [comment]
There, I removed them. Thanks!

**Comment by shermida** [comment]
Fixed.
