### ISSUE TITLE
#6629 Frontend: Multimedia Objects: Publication: Broadcast: MO with Broadcast Corporative returns 404 on click Url link

### ISSUE THREAD

**Issue by bmartinezteltek** [campusdomar/PuMuKIT2#19]
Using broadcast Corporative and PubChannel WebTV should ask for user and password when clicking the video link.

**Comment by mreyk** [comment]
Commit 8639032

**Comment by bmartinezteltek** [comment]
Using broadcast Corporative and broadcast Private the videos can be played without asking for credentials (user, password) as if they were using broadcast Public.

**Comment by bmartinezteltek** [comment]
Bug tested with admin role.

**Comment by bmartinezteltek** [comment]
Using Publisher role and broadcast Corporative it returns 404 on clicking Url link. The videos are not shown in the series. Also, Status (Published, Hidden, Blocked) can not be changed

**Comment by mreyk** [comment]
Feature: Publisher user can not change the status of a Multimedia Object.
Frontend: Backend user is not related to Broadcast profiles, so you should be able to watch the video.
It works for me. Try again.

**Comment by bmartinezteltek** [comment]
Ok. 
The bug is present when you use a MO imported from the Opencast Ingester. Using Corporative or Private broadcast and  WebTV Publication Channel, should ask for user and password when clicking the video link. Currently you can play the recording despite the fact the MO has Private or Corporative broadcast.

**Comment by mreyk** [comment]
Fixed in commit 23599f603d8e0864752b1b7c60f9fcfac4097168

Test again.

**Comment by bmartinezteltek** [comment]
Using broadcast Private the videos are shown in the frontend. Only Corporative and Public videos should be shown in the frontend.

**Comment by bmartinezteltek** [comment]
MO with Broadcast Corporative or Private ask for user/password to play the video on the frontend. If you click on the "Cancel" button of the user/password form Pumukit should redirect to the previous page (Current series on the frontend). Now it just loads a white page with no content.

**Comment by mreyk** [comment]
Fixed in commits 018be5daf358c6d642ffa5e07a7276463304a74c e5175c715203df0ab19e259ef6df4421e94f2325 38d749260bf89b56d855a12487803aefe5234123 ce3d36ab27a937b171b8079bab9c43490e009633 f2bb629c62c81a2e27637fba2a2c66dc3596b845

Test again.

**Comment by bmartinezteltek** [comment]
Redirect to the previous page (Current series on the frontend) not implemented yet.

**Comment by mreyk** [comment]
Fixed in commit a8a2d5a7e633d4096b2ae9a09b4515a3ee4c7a32

**Comment by bmartinezteltek** [comment]
Tested OK.
