### ISSUE TITLE
Moodle Playlist: Recycle Magic URL icon visible for users without permission

### ISSUE THREAD

**Issue by shermida** [campusdomar/PuMuKIT2#197]
**Steps:** 

- Log in with an autopublisher user

- Click in Media Manager >> Series

- If there is any multimedia object, delete it. Now the user can not admin any MO.

- Click in Media Manager >> Playlist

- Select a multimedia object and click the recycle magic url icon ![recycle_icon](https://cloud.githubusercontent.com/assets/19668673/16728918/836cf162-4769-11e6-91b1-ed46c0b09bb4.png)

**Result:**

The following error is shown. 

![magic url](https://cloud.githubusercontent.com/assets/19668673/16728835/133cef14-4769-11e6-82ef-c7eda68daabf.png)

**Expected result:**

The recycle icon should not be shown.

**Comment by Alfro** [comment]
Given that we can already reset the magic url form the Multimedia Object edition tab (on its own series), we should actually remove that option altogether.

**Comment by Alfro** [comment]
@shermida Can you take a look at this again?

**Comment by shermida** [comment]
The recycle magic url icon has been renoved from the Playlist. Issue fixed.
