### ISSUE TITLE
Moodle Playlist: Search playlist from different page gets 500 error

### ISSUE THREAD

**Issue by shermida** [campusdomar/PuMuKIT2#205]
**Steps:**

- Click in Media Manager >> Moodle Playlist

- Click in page 2

- Search one playlist from another page, for example "New"

**Result:**

The server returned a 500 Internal Server Error. 

- Click the Web Browser return button 

- Click page 3 >> 500 Internal Server Error

- Click the Web Browser return button again

- Click page 1 >> List with every playlist with the name "New"

**Comment by Alfro** [comment]
It's actually easier to replicate.
**Steps:**
* Add `'&page=NUM'` to the url, where `NUM` is bigger than the last page
:smile:

**Comment by Alfro** [comment]
@shermida It should be fixed now.

**Comment by shermida** [comment]
It is fixed.
