### ISSUE TITLE
Problem with some old web browsers

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT2#206]
Steps:
- Log in in pumukit

Problem: As you can see in the attached picture, the checkbox in series is not visible and you cannot select a series clicking on it. It happens in some versions of web browser, as for example: chrome 46.0.2490.80 (64-bit) or Internet explorer 11 (11.09600.18349). For example in chrome version 49.0.2623.110 works correctly.

![checkbox](https://cloud.githubusercontent.com/assets/11191010/16809975/779b0d96-4922-11e6-8959-e2722fc3478c.png)

**Comment by rubenrua** [comment]
commit https://github.com/campusdomar/PuMuKIT2/commit/028a8d969e419e58d6160b513b8e8cc9c001171b

**Comment by silviabf** [comment]
The checkbox is visible in these old versions now. I close this issue.
