### ISSUE TITLE
Moodle Playlist: Autopublisher do not see his videos in "My Videos" 

### ISSUE THREAD

**Issue by shermida** [campusdomar/PuMuKIT2#207]
**Steps:**

- Log in as an Autopublisher

- If the user do not have videos in Series, upload one video

- Creat a new Playlist and click "Add" inside the playlist

- Click in "My Videos" 

**Result:**

It is loading all the time and no videos are shown.
![my videos empty](https://cloud.githubusercontent.com/assets/19668673/16811199/8796c5b4-4927-11e6-8934-6f4b98f483b5.png)

**Comment by Alfro** [comment]
The bug would happen if you didn't have many objects. My bad :)
@shermida Check it out. It should work correctly now.

**Comment by shermida** [comment]
It works correctly now.
