### ISSUE TITLE
Naked Backoffice:Tabs unselected when you select the videos in a playlist or series

### ISSUE THREAD

**Issue by Alfro** [campusdomar/PuMuKIT2#208]
### Moved from: teltek/PuMuKIT2-moodle-bundle#20

Steps:
- Enter in moodle repository
- Click on videos in any series or any playlist

Problem:
As you can see in the attached picture, the upper menu tabs are unselected and you do not know if you are into a playlist or into a series

![tabs](https://cloud.githubusercontent.com/assets/11191010/16810473/45c3bdca-4924-11e6-97f7-ef92076f33fe.png)

**Comment by Alfro** [comment]
@silviabf Take a look at it. It should be fixed now.

**Comment by silviabf** [comment]
Fixed in the videos, but it continues happen when you click on wizard (in series or videos) as you can see in the attached picture
![wizard](https://cloud.githubusercontent.com/assets/11191010/16841328/fbb8148c-49d8-11e6-9fa6-ef86ef3fb2c5.png)

**Comment by Alfro** [comment]
@silviabf My bad.
I added the wizard now to be highlighted as part of the 'Multimedia Series' menu.

**Comment by silviabf** [comment]
Fixed. I close this issue.
