### ISSUE TITLE
Rare state after remove a user from a video

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT2#209]
Steps:
- Select any video in pumukit
- Go to people and add a user in any role of the video
- Delete the user you just added

Problem: After delete the user, the message that you can see in the attached picture is shown. The user is correctly deleted and if you reload the page the message dissapeared
![delete](https://cloud.githubusercontent.com/assets/11191010/16836684/ff02d934-49be-11e6-93f5-137be329d360.png)

**Comment by Alfro** [comment]
What you are adding are **People**, not **users**. The distinction is important since Users/People are related to each other 1:1

**Comment by Alfro** [comment]
@silviabf Not it is fixed, and it does not show the weird link.
Though other bugs could appear related to this one, I am afraid.

**Comment by silviabf** [comment]
This bug is fixed. I close this issue. I look for if there is any bug related with this.
