### ISSUE TITLE
#6606 Backend: Management : Admin Users: Delete Admin and Publisher users

### ISSUE THREAD

**Issue by bmartinezteltek** [campusdomar/PuMuKIT2#21]
You can delete all Admin and Publisher users if it remains a User user.

**Comment by mreyk** [comment]
Fixed in commit 867ec5bb9820ca24eb9a0b28d1cc8f7b221e6c75

**Comment by bmartinezteltek** [comment]
If you are logged as Admin user and you delete all the users except the your Admin user, the Admin user is deleted.

**Comment by mreyk** [comment]
Fixed in commit 80d53465c5fee3549d2e1ef2054167652d83d45d

**Comment by bmartinezteltek** [comment]
If you are logged as Admin user and you delete all the users except  your Admin user, it only deletes one user.

**Comment by mreyk** [comment]
Test again. Code was not updated.

**Comment by bmartinezteltek** [comment]
Tested OK.
