### ISSUE TITLE
Videos with moodle publication channel only are shown in Web Tv preview (magic url)

### ISSUE THREAD

**Issue by Alfro** [campusdomar/PuMuKIT2#210]
### Migrated from teltek/PuMuKIT2-moodle-bundle#30
**Steps:**
- ~~Enter in Moodle repository~~ *Reproducible through the regular back-office.*
- Create a series with 2 videos (one with publication channel web tv and one with publication channel moodle)
- Modify state of the videos: hidden to the web tv video and published to the moodle video
- Go to magic url from the hidden video

**Problem:**
In the preview of the video, you can see in the section "videos from the same series" the video that have moodle publication channel. This video does not have preview in the web (it has not either magic url) and if you click on it you have a 404 error. You can see it in the attached picture (video de prueba 1 and video prueba 4 have only moodle publication channel marked) and they are visibles. If you use the real url, then the moodle videos are not shown.
![preview](https://cloud.githubusercontent.com/assets/11191010/16838202/5bbfa798-49c8-11e6-80e5-ac314f96b504.png)

**Comment by Alfro** [comment]
@silviabf There, it should work properly now.

**Comment by silviabf** [comment]
Fixed, videos with moodle publication channel are not shown in magic url of a hidden video. I close this issue.
