### ISSUE TITLE
Option Announce/Non announce selected is available in the dropdowns when "last added" is disabled in pumukit configuration

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT2#211]
Steps:
- Deactivate in pumukit configuration the possibility of mark the series or videos as last added in the frontend
- Go to pumukit backoffice
- Select any series and go to "Select an action" dropdown

Problem: There is an option "Announce/Non announce selected" in series list and in videos list. This option only activate the icon of announce, it does nothing in the frontend.

**Comment by rubenrua** [comment]
@silviabf  It should be fixed now.

**Comment by silviabf** [comment]
Fixed. The option is not selectable now when "Last added" is disabled. I close this issue.
