### ISSUE TITLE
Synchronize Tags of a video in a series, it synchronizes the publication channels also

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT2#212]
Steps:
- Enter in pumukit backoffice (with moodle and youtube bundles installed)
- In a series, upload three videos, one with moodle publication channel, other with youtube and other with WebTV
- In one of the three videos go to Tags and add any tag.
- Then, click on "Sync in this series"

Problem: The tags are synchronized in the three videos, but also the publication channel is syncronized, and the three videos have the same publication channel.

**Comment by Alfro** [comment]
@silviabf It should be fixed now.

**Comment by silviabf** [comment]
Fixed. Publication channels are not synchronized now. I close this issue.
