### ISSUE TITLE
Add MO to Playlist: It is not possible to select one video

### ISSUE THREAD

**Issue by shermida** [campusdomar/PuMuKIT2#213]
**Steps 1:**

- Log in with an Autopublisher User.

- If the user do not have any series with videos, create one and add some MO to it. 

- Create a Playlist and click in Add

- Select "My Videos" tab

- Select one video to add

**Result 1:**

It is not possible to select one video, so it is impossible to add videos one by one.

**Steps 2:**

- Now click in Search

- Try to do a successfully search

- After that click in My Videos tab again

- Select one video

**Result 2:**

Now it is possible to select videos.

**Expected Result:**

It should not be necesary to do this to be able to add a selected video.

**Comment by Alfro** [comment]
@shermida Videos are actually selected. If you noticed, the 'Add Video' changes when you click on a video.
The bug is about the orange box not appearing to mark when a video is selected.

**Comment by Alfro** [comment]
@shermida Now it should indicate which elements are selected with the orange-box.
(Make sure that you can still add elements correctly through all tabs.)

**Comment by shermida** [comment]
It is fixed.
