### ISSUE TITLE
Add MO to Playlist: Not all videos are listed in My Videos

### ISSUE THREAD

**Issue by shermida** [campusdomar/PuMuKIT2#214]
**Steps:**

- Create a Series with more than 20 MO or log in with the Autopublisher user available

- In playlist, create a new playlist and clic in Add to add videos

- Click in My Videos. 

**Result:**

If there is 22 videos in Series, only the last 2 videos are shown:
![videos 21 y 22](https://cloud.githubusercontent.com/assets/19668673/16912142/c9a7d218-4ce2-11e6-84a3-607a0c49abbd.png)

If another video is added, then only 3 videos will be shown in My Videos.

**Expected Result:**

All videos should be listed.

**Comment by Alfro** [comment]
@shermida It should be fixed now.

**Comment by shermida** [comment]
It is fixed.
