### ISSUE TITLE
#6539 Backend: Create new from the list options is redundant

### ISSUE THREAD

**Issue by bmartinezteltek** [campusdomar/PuMuKIT2#24]
There is already a New button to create new objects. 

It is present in:

Live: Live Events
Live: Live Channels
Tables: People
Management: Admin Users
Management: Roles
Management: Access Profiles

**Comment by mreyk** [comment]
Fixed in commits 1077f27ad567ef6764537e1f2859628b197084a1 011d7a5ab076a27dbcee3c814b4b38fddcb365b9

**Comment by bmartinezteltek** [comment]
It is also present in Tables: Series types

**Comment by mreyk** [comment]
Fixed in commit 66891081ff46ab09a133f79d4183ac616f4daf60

**Comment by bmartinezteltek** [comment]
Tested OK.
