### ISSUE TITLE
#6383 Backend: Multimedia series: Videos template: Tags : Error in Tag counter

### ISSUE THREAD

**Issue by bmartinezteltek** [campusdomar/PuMuKIT2#29]
Steps :

- Select a series.
- Add a tag with counter 0 from videos template.
- Create a MO with the New button inside the series.
- Remove the tag from the MO.
- Remove the tag from videos template.

The tag counter is -1

Steps with the "Sync in this series" button :

- Add a tag with counter 0 from videos template and click "sync in this series".
- Remove the tag from videos template and click "sync in this series".

The tag counter is -1

It also happens if the tag is removed from a MO and then is clicked "sync in this series".

**Comment by mreyk** [comment]
Fixed with commits ce25ed6cef5962fb94e8fdcb740fe7ea8fd0ee23 8ccfd90a7f74613e27dfcd9bb18cf276cc47cfe6 dc50269f67973f50e429059c3682c1d73c023696

**Comment by bmartinezteltek** [comment]
Tested OK.
