### ISSUE TITLE
Track framerate: change it from integer to string

### ISSUE THREAD

**Issue by mreyk** [campusdomar/PuMuKIT2#32]
Using ffprobe or avprobe gives framerate value as 'frames/seconds'. Framerate field in document Track is defined as an integer instead of string. So, we need to make different changes in document Track as in other services to make this work properly.

**Comment by mreyk** [comment]
Commit 1989443ee1ed62e987f19073fe99c2bfc05dec52

**Comment by mreyk** [comment]
Added second commit

**Comment by bmartinezteltek** [comment]
Tested. OK.
