### ISSUE TITLE
Installation Guide: Review sudo steps in the guide

### ISSUE THREAD

**Issue by bmartinezteltek** [campusdomar/PuMuKIT2#34]
/var/www Permissions thread : http://askubuntu.com/questions/162866/correct-permissions-for-var-www-and-wordpress

You need to create /var/www/pumukit2 directory as a root , then follow the Permissions thread to allow the local user to access the directory (add local user to www-data group).

**Comment by mreyk** [comment]
commit e306b2616c117b7b983a8fac0dbd95c1a01103da

Fixed in branches: 2.1.x, master
Fixed in tag: 2.1.0-RC1

**Comment by bmartinezteltek** [comment]
sudo Steps added to the Installation Guide.
