### ISSUE TITLE
Installation Guide: Add php.ini timezone configuration in Step 6 /app_check.php 

### ISSUE THREAD

**Issue by bmartinezteltek** [campusdomar/PuMuKIT2#35]
You need to configure your timezone ("Europe/Madrid") in /etc/php5/cli/php.ini file.

**Comment by mreyk** [comment]
commit e306b2616c117b7b983a8fac0dbd95c1a01103da

Fixed in branches: 2.1.x, master
Fixed in tag: 2.1.0-RC1

**Comment by bmartinezteltek** [comment]
Tested OK.
