### ISSUE TITLE
Installation Guide: Add cache clear to production environment in step 6

### ISSUE THREAD

**Issue by bmartinezteltek** [campusdomar/PuMuKIT2#36]
php app/console cache:clear --env=prod

**Comment by mreyk** [comment]
commit 054ceb01bbb7f8d0e1058bb5d85bac973aa49c86

Fixed in branch 2.1.x and master
Fixed in tag 2.1.0-RC1

**Comment by bmartinezteltek** [comment]
Tested OK.
