### ISSUE TITLE
Installation Guide: Problem with Composer installation in step 5: Need to generate a personal Token on Github

### ISSUE THREAD

**Issue by bmartinezteltek** [campusdomar/PuMuKIT2#37]
API rate limit and OAuth tokens#

Because of GitHub's rate limits on their API it can happen that Composer prompts for authentication asking your username and password so it can go ahead with its work.

https://getcomposer.org/doc/articles/troubleshooting.md#api-rate-limit-and-oauth-tokens

**Comment by mreyk** [comment]
commit 054ceb01bbb7f8d0e1058bb5d85bac973aa49c86

Fixed in branch 2.1.x and master
Fixed in tag 2.1.0-RC1

**Comment by bmartinezteltek** [comment]
Added to the FAQ section OK
