### ISSUE TITLE
Backend: Encoder: Task error, info button

### ISSUE THREAD

**Issue by bmartinezteltek** [campusdomar/PuMuKIT2#39]
Info button do not respond. 
![bug_pmk2_encoder_error](https://cloud.githubusercontent.com/assets/12255927/8426869/4434fe9c-1f13-11e5-9372-1fe150437f8a.png)

**Comment by bmartinezteltek** [comment]
Clicking the info button of the error task generates a hanging of several seconds on the backend.

**Comment by mreyk** [comment]
Commits: cb45269b0f3694315e4ce1c022ecdd1f61fab682 18c4a4c1109c7439e87827c98feba6561713a701

**Comment by bmartinezteltek** [comment]
Info button OK.

Problem with Retry button: Permission denied message when retrying to transcode the error task.

**Comment by mreyk** [comment]
Try again.

**Comment by bmartinezteltek** [comment]
Tested OK.
