### ISSUE TITLE
Step of development environment

### ISSUE THREAD

**Issue by ivanoterouvigo** [campusdomar/PuMuKIT2#4]
In installation guide, the firs step of development environment:

# User develop
git checkout develop

I have the following error:
fatal: Unable to create '/var/www/pumukit2_001/.git/index.lock': Permiso denegado

I try to fix it following this link: http://stackoverflow.com/questions/7860751/git-fatal-unable-to-create-path-my-project-git-index-lock-file-exists

Conclusion:

rm -f ./.git/index.lock 

and the if console gave an error message. Then, try

rm -Force ./.git/index.lock

However I think you want to say:
# User develop
git checkout -b develop

with this you create a new branch with name develop

Is it that you want??

**Comment by mreyk** [comment]
The error is because you don't have any local branch named develop. So, that's right, we should checkout to a new branch only the first time.

```
$ git checkout -b develop
```

**Comment by mreyk** [comment]
Commit: 20696450
