### ISSUE TITLE
Frontend: Series with videos imported from Opencast doesn't have preview

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT2#41]
Steps:
* Import a video from opencast
* Publish the video
* Go to frontend and select the series of this video

The series only shows the title, the videos preview box is not shown.

**Comment by rubenrua** [comment]
Pumukit should use `opencastdisplay` property and not `opencasthide`.

**Comment by mreyk** [comment]
Fixed in commit 2817d3c9ce661882d4331ffcf7af7d1ebf2dd0da

**Comment by bmartinezteltek** [comment]
Tested OK.
