### ISSUE TITLE
Backend: Management: Admin users: Last admin user can be edited and converted in Publisher or User

### ISSUE THREAD

**Issue by bmartinezteltek** [campusdomar/PuMuKIT2#45]
Last Admin user can be edited and change his privileges. As a result, last Admin user can be converted in User user. Then  if you log out and you log in again you can not access the backend (User case) or the Admin users module (Publisher case).

**Comment by mreyk** [comment]
Fixed in commit c4931ecf3555f73a396b098a9ecaf21ece80b454

**Comment by bmartinezteltek** [comment]
Tested OK.
