### ISSUE TITLE
Backend: Multimedia objects: Publication: Published videos with no delivery copy returns 404 Error

### ISSUE THREAD

**Issue by bmartinezteltek** [campusdomar/PuMuKIT2#47]
Steps : 

- Create a MO and upload a video file.
- Mark "Published" status and "WebTV" publication channel.
- Go to the frontend to play the video.

If the delivery copy has already been created before playing the video, try to remove the delivery copy and go again to the frontend to play the video.

It returns a 404 Error. See attached image.
![captura de pantalla de 2015-09-16 13 39 00](https://cloud.githubusercontent.com/assets/12255927/9904236/863a7fb4-5c7c-11e5-9225-08fab4989c06.png)

**Comment by mreyk** [comment]
Fixed in commit 44ca954fc5c758058fd16de4f87472a3a4f11869

Test again.

**Comment by bmartinezteltek** [comment]
If there is no delivery copy the video should not be accesible on the frontend. RM task: #7892

**Comment by bmartinezteltek** [comment]
Tested OK.
