### ISSUE TITLE
Install PuMuKIT with the branch 2.1.x 

### ISSUE THREAD

**Issue by agusave82** [campusdomar/PuMuKIT2#72]
In the installation guide when performing step 7,

7. Install dependencies and provide PuMuKIT-2 parameters:

 php composer.phar install

the following error occurs

Could not fetch https://api.github.com/repos/sebastianbergmann/php-code-coverage/zipball/fe2466802556d3fe4e4d1d58ffd3ccfd0a19be0b, please create a GitHub OAuth token to go over the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+pcdev0003+2016-03-04+1257
to retrieve a token. It will be stored in "/home/amartinez/.composer/auth.json" for future use by Composer.
Token (hidden):

**Comment by Alfro** [comment]
This is an issue with the GitHub API for anonymous users. Following those instructions (that composer prints) will provide you with a token to prevent that issue.

I added a link to the manual's [F.A.Q](https://github.com/campusdomar/PuMuKIT2-doc/blob/026b74b62d8a3aa3c0287280692840990356c045/InstallationGuide.md#add-github-token) after the step 7, just in case.
