### ISSUE TITLE
Install PuMuKIT with the branch 2.1.x: error in the link to the Symfony documentation

### ISSUE THREAD

**Issue by agusave82** [campusdomar/PuMuKIT2#73]
when you execute step 8 in the installation guide,

8. Give cache and log directories the right permissions.
    
- Follow the instructions at Symfony (documentation).

The link goes to version 3.0 and has to go to version 2.6

**Comment by Alfro** [comment]
The correct link to the Symfony Docs was now added.
Closing issue
