### ISSUE TITLE
Upload files with wizard: File upload must be less than 2 MB

### ISSUE THREAD

**Issue by agusave82** [campusdomar/PuMuKIT2#74]
The steps are as follows:

1. Go to PuMuKIT
2. Upload a video with wizard
3. In the step 4: file
Upload the multimedia file

Error:

You can not upload files that exceed 2MB
![error_upload_wizard](https://cloud.githubusercontent.com/assets/17157560/13574945/ae913f24-e486-11e5-846a-b29a925a6901.png)

**Comment by Alfro** [comment]
That is a php configuration issue. In the manual's [F.A.Q](https://github.com/campusdomar/PuMuKIT2-doc/blob/026b74b62d8a3aa3c0287280692840990356c045/InstallationGuide.md#4-faq) it explains how to configure this limit to make it bigger.

**Comment by vgoya** [comment]
The PHP limit is 2MB or 2GB ?

**Comment by Alfro** [comment]
@vgoya The PHP default upload limit is 2MB.
Should we add changing this value as a **step** in the InstallationGuide?

**Comment by rubenrua** [comment]
> Should we add changing this value to a bigger one as a step in the InstallationGuide? (instead of the F.A.Q)

@Alfro. +1 to add a step  to update `php.ini` with `post_max_size ` and `upload_max_filesize ` (like  update `date.timezone` in the step 9).

PuMuKIT1 installation guide had this point: https://github.com/campusdomar/PuMuKIT1/blob/master/doc/InstallationGuide.md

**Comment by vgoya** [comment]
Recommended default configuration should be 2GB. 2MB is uselessl for video upload

**Comment by Alfro** [comment]
I added it to the docs as step 17 of the single node installation: 
https://github.com/campusdomar/PuMuKIT2-doc/blob/2.1.x/InstallationGuide.md#2-single-node-installation-on-linux-ubuntu-1404

**Comment by rubenrua** [comment]
TODO
 * Join all the steps about changing `php.ini` in the same step.
 * Use `sed` to chage `php.ini` like step 9.

**Comment by Alfro** [comment]
Done.
Closing issue.
