### ISSUE TITLE
Channels: 'University' Channel throws an error (migrating from 2.1 to 2.2

### ISSUE THREAD

**Issue by Alfro** [campusdomar/PuMuKIT2#75]
This is because the new editorial decision 'PUDEUNI' is not added when migrating.

Adding logic to the doc/updateModel_2.1_to_2.2 script

**Comment by Alfro** [comment]
This should be fixed now.

**Comment by Alfro** [comment]
@agusave82 Do as in #79

**Comment by agusave82** [comment]
I returned to testing QA,

Now I can access different parts of the portal video correctly.

Closing issue
