### ISSUE TITLE
When creating a new series, appears in the video portal as recently added

### ISSUE THREAD

**Issue by agusave82** [campusdomar/PuMuKIT2#76]
The steps are as follows:

1. Create a new serie with wizard or new 
2. Once created go to video portal

Error:
The series created appears as recently added (the option recently added is uncheck)

**Comment by Alfro** [comment]
It should be fixed now.

**Comment by agusave82** [comment]
I returned to testing QA,

The bug has been fixed and the series created not appear in "recently added".

But still they appear in "Latest uploads"
![latest_uploads](https://cloud.githubusercontent.com/assets/17157560/13596800/149f23c4-e515-11e5-814e-f8fe28b0561d.png)

**Comment by Alfro** [comment]
@agusave82 My bad, I didn't think it would be fauiling there too. It should be fixed now as well.

**Comment by agusave82** [comment]
@Alfro now is fixed in latest upload.
Closing issue
