### ISSUE TITLE
Failed when trying to enter categories, multimedia object search and by subject catalogue

### ISSUE THREAD

**Issue by agusave82** [campusdomar/PuMuKIT2#79]
It fails when trying to enter the following parts of the video portal:

- Categories.
- Multimedia objects search.
- By subject catalogue.

![error_search_multimedia_objects](https://cloud.githubusercontent.com/assets/17157560/13597174/615bf208-e517-11e5-9eab-820ed6874541.png)

**Comment by agusave82** [comment]
@Alfro this error is related to the update made to correct the bug #76?

**Comment by Alfro** [comment]
@agusave82 It shouldn't.
Can you try entering through the developer enviroment? A screen capture of the actual error would be quite helpful.

**Comment by agusave82** [comment]
@Alfro  This is the screen capture of actual error when trying access to categories

![error_categories](https://cloud.githubusercontent.com/assets/17157560/13598374/bcaf6dbe-e51d-11e5-9916-e95f279c7f19.png)

**Comment by agusave82** [comment]
@Alfro and this is the screen capture when trying access to multimedia object search and by subject catalogue
![error_multimedia_object_search](https://cloud.githubusercontent.com/assets/17157560/13598459/260f1b2e-e51e-11e5-9624-c10365823c55.png)

**Comment by Alfro** [comment]
Ah, as I thought. This is related to #75 
Once that is fixed, this will be too.

**Comment by agusave82** [comment]
Ok,
Once this fixed I repeat tests

**Comment by Alfro** [comment]
I updated the doc/updateModel_2.1_to_2.2.php command. Now it should propertly initialize the tags.

@agusave82  Try to pull the new code and execute this command again:
```bash
php doc/updateModel_2.1_to_2.2.php update:model:2.1to2.2
```

**Comment by agusave82** [comment]
I returned to testing QA,

Now I can access different parts of the portal video correctly.

Closing issue
