### ISSUE TITLE
Images from advanced images generator aren't shown using Safari

### ISSUE THREAD

**Issue by iriadp** [campusdomar/PuMuKIT2#793]
Steps to reproduce it:
- Access the backoffce using Safari (IOS or Windows).
- Go to a MMO, to the multimedia tab.
- Using the advanced images generator take a burst of images.

Error: With Safari images do not appear correctly.
Expected behaviour: They should appear to let us choose the one we want.

**Comment by rubenrua** [comment]
See https://bugs.webkit.org/show_bug.cgi?id=17352

**Comment by iriadp** [comment]
Solved with the lastest version of Safari
