### ISSUE TITLE
#6750 Installation Guide: Backend: Multimedia Objects: Multimedia: Transcoding error, ffmpeg not found

### ISSUE THREAD

**Issue by bmartinezteltek** [campusdomar/PuMuKIT2#8]
Profile transcoding commands that use the ffmpeg command does not work with mediainfo libav-tools.
 Php5-ffmpeg and ffmpeg are not installed on the machine.

**Comment by rubenrua** [comment]
Commits:  f51aeec6e02ebcc749a28d30d5f6309d1b13813e, df49d7eaa75736094d6495314ec4961b2dda9afe, 8ff4d44868995eb7219f5aaa6ecfe2c5ca7555f3, 66fab47870976e412b5db8d132e1297eb9e70eac

**Comment by rubenrua** [comment]
The recommended tool to use with Pumukit is the [libav-tools](https://libav.org/) package, which is available to install from the official repositories for all Debian-based distributions like Ubuntu.

You can still use [ffmpeg](https://www.ffmpeg.org/) changing the configuration file. A cookbook will be written with the recipes needed to use it.

**Comment by bmartinezteltek** [comment]
Tested. OK.
