### ISSUE TITLE
Back-office: The mmobjs don't have a player by default

### ISSUE THREAD

**Issue by Alfro** [campusdomar/PuMuKIT2#80]
In the back-office, it was possible before to visualize the videos directly on the back-office. We moved this player to the 'video-editor' tab now, thus removing the video player if there is no video editor bundle installed.

_User story:_
- As a back-office user, I want a way to visualize my videos directly from the back-office without installing external bundles.

**Comment by rubenrua** [comment]
Waiting for the new backoffice.

**Comment by iriadp** [comment]
Pumukit now includes a preview for the videos.
