### ISSUE TITLE
#9834 Install PuMuKIT with the branch 2.1.x: error in the order of steps in the installation guide

### ISSUE THREAD

**Issue by agusave82** [campusdomar/PuMuKIT2#81]
There is an error in the order of instructions. 

The instruction number 16,

16. Add NGINX config file.

`sudo cp doc/conf_files/nginx/default /etc/nginx/sites-available/default`

It must be executed before instruction number 11

11. Check environment requirements:

- Go to `http://{PuMuKIT-2-HOST}/config.php` for checking requirements.

- Fix errors if any and restart PHP5-FPM service. Fix warnings if necessary (PDO drivers are not necessary for PuMuKIT-2 to work). `sudo service php5-fpm restart`

- Check requirements again

- Repeat all steps until the MAJOR PROBLEMS list disappears.

Then you have to execute the instruction number 18,

18. Restart server

`sudo service php5-fpm restart`
`sudo service nginx restart`

**Comment by Alfro** [comment]
Added correctly to documentation

**Comment by agusave82** [comment]
Fixed
Closing issue
