### ISSUE TITLE
Implement the *clone multimedia object* functionality to clone everything.

### ISSUE THREAD

**Issue by Alfro** [campusdomar/PuMuKIT2#83]
**Use story:**
* As a back-office user, I want to be able to clone a multimedia object so that I can publish differently edited versions of the same video.

**Task:**
* Implement cloning tracks, pics, attachment and multimedia objects on their respective services.
* Replace the current function of '*Clone multimedia object*' with this functionality.
* Add extra check when a track/mmobj/attachment/series is deleted (not to delete files being used by another resource).

Note: When cloning a multimedia object, also have into account the *Annotations* of that multimedia object and clone them as well.

**Comment by Alfro** [comment]
@agusave82 Please, test this new feature.

**Comment by agusave82** [comment]
@Alfro I am with this now

**Comment by agusave82** [comment]
I returned to testing QA,

This bug is fixed.

Closing issue
