### ISSUE TITLE
Video Portal: Languages: change language to Spanish

### ISSUE THREAD

**Issue by agusave82** [campusdomar/PuMuKIT2#84]
If we change the language to Spanish, the titles of  menus are in English

![error_languague_spanish](https://cloud.githubusercontent.com/assets/17157560/13606850/f4fad2dc-e54d-11e5-9675-98c199237dc1.png)

**Comment by Alfro** [comment]
Change breadcrumb titles.

**Comment by Alfro** [comment]
@agusave82 Try it again, it should be translating correctly now.

**Comment by agusave82** [comment]
@Alfro I returned to testing QA,

This bug is fixed.

Closing issue
