### ISSUE TITLE
Video Portal: Share this video: iframe

### ISSUE THREAD

**Issue by agusave82** [campusdomar/PuMuKIT2#85]
The steps are as follows:

1. go to the back-office
2. upload a video with several tracks
3. transcode to profile h_264

![transcode_to_profile_h264](https://cloud.githubusercontent.com/assets/17157560/13607664/84ff72ea-e551-11e5-82da-46a0aa8badd1.png)

4. publish the video
5. Go to video portal
6. Enter in all videos and check the iframe 

![videos](https://cloud.githubusercontent.com/assets/17157560/13607770/f40046ba-e551-11e5-896a-bb556a3df614.png)

Error:
The iframe is the same for all videos

**Comment by Alfro** [comment]
Todo: Add track to the iframe url of the video.

**Comment by Alfro** [comment]
Fixed. It should work now after updating the code to the last version

**Comment by agusave82** [comment]
I returned to testing QA,

This bug is fixed.

Closing issue
