### ISSUE TITLE
Back-office: Add proper warning when opencast is not propertly configured

### ISSUE THREAD

**Issue by Alfro** [campusdomar/PuMuKIT2#87]
*Use story:*
* As a back-office administrator, I want to know which parameters from the opencast configuration are incorrect and why so that I can locate and correct them easily.

As of now, the opencast bundle shows quite a simple error message if it can't connect or if there is a misconfiguration.
![opecast](https://cloud.githubusercontent.com/assets/11334172/13606497/657d4c76-e54c-11e5-9c85-3b6b783e1acc.png)

We should make it more specific to the parameter that is failing.

**Comment by rubenrua** [comment]
Done
