### ISSUE TITLE
#9835 Install PuMuKIT with the branch 2.2.x: "UCies" appears in the terminal

### ISSUE THREAD

**Issue by agusave82** [campusdomar/PuMuKIT2#88]
In the installation process, executing step 7,

7. Install dependencies and provide PuMuKIT-2 parameters:

`php composer.phar install`

It appears on the terminal "UCies"

![bug_ucies tv](https://cloud.githubusercontent.com/assets/17157560/13634543/7e158488-e5f6-11e5-8da5-e4b00e8867c7.png)

**Comment by Alfro** [comment]
Fixed. Try reinstalling from the start again and see if the default parameters are now 'PuMuKIT' ones.

**Comment by agusave82** [comment]
I reinstalled from scratch and now the default parameters are correct.

closing issue
