### ISSUE TITLE
Backoffice: MultimediaObject/Tag: Can't search on tags

### ISSUE THREAD

**Issue by Alfro** [campusdomar/PuMuKIT2#884]
The tags search on each tag type does not seem to work.
![screenshot from 2018-10-24 17-25-20](https://user-images.githubusercontent.com/11334172/47442023-d6ef7280-d7b1-11e8-9e81-c95d3d9f5147.png)

It shows a js error.

**Comment by iriadp** [comment]
Can't be replicated
