### ISSUE TITLE
#6748 Installation Guide: if no access to /app_dev.php

### ISSUE THREAD

**Issue by bmartinezteltek** [campusdomar/PuMuKIT2#9]
In case nor localhost/app_dev.php nor localhost/app_dev/admin are available you have to comment the following if condition in web/app_dev.php : 

/*
if (isset($_SERVER['HTTP_CLIENT_IP']) || isset($_SERVER['HTTP_X_FORWARDED_FOR']) || !(in_array(@$_SERVER['REMOTE_ADDR'], array('127.0.0.1', 'fe80::1', '::1')) || php_sapi_name() === 'cli-server')
) {
header('HTTP/1.0 403 Forbidden');
exit('You are not allowed to access this file. Check '.basename(FILE).' for more information.');
}
*/

**Comment by mreyk** [comment]
commit 054ceb01bbb7f8d0e1058bb5d85bac973aa49c86

Fixed branches: 2.1.x, master
Fixed in tag: 2.1.0-RC1

**Comment by bmartinezteltek** [comment]
Tested OK.
