### ISSUE TITLE
#9903 Pumukit 2.2.x: stadistics module: series: most viewed series: the button "next" not work

### ISSUE THREAD

**Issue by agusave82** [campusdomar/PuMuKIT2#90]
If I'm on page one and want to go to page 2 with the button "next", doesn't work.

![next_not_work](https://cloud.githubusercontent.com/assets/17157560/13642537/334469a2-e61d-11e5-888e-cf03e4a5b54b.png)

**Comment by Alfro** [comment]
@agusave82  Reinstall the stats bundle and try it now. It should work propertly

**Comment by agusave82** [comment]
@Alfro I reinstalled the stats bundle but the bug is still playing

**Comment by agusave82** [comment]
I returned to testing QA,

This bug is fixed.

Closing issue
