### ISSUE TITLE
#9903 PuMuKIT 2.2.x: stadistics module: series: views by time period: days

### ISSUE THREAD

**Issue by agusave82** [campusdomar/PuMuKIT2#92]
Don't match visits between days and months. The number of visits in days begins in July 2015.

![days](https://cloud.githubusercontent.com/assets/17157560/13663915/a1e13246-e6a4-11e5-8d54-e0bfdb173d7b.png)

The number of visits in months begins in March 2014

![months](https://cloud.githubusercontent.com/assets/17157560/13663932/bc7b9d80-e6a4-11e5-8366-5504339e0add.png)

**Comment by Alfro** [comment]
Fixed for now

**Comment by agusave82** [comment]
I returned to testing QA,

This bug is fixed.

Closing issue
