### ISSUE TITLE
#9903 Pumukit 2.2.x: stadistics module: series: most viewed objects: delete multimedia object

### ISSUE THREAD

**Issue by agusave82** [campusdomar/PuMuKIT2#94]
If a multimedia object is deleted, it is still displayed in "all objects" and "showing"

![delete_multimedia_object](https://cloud.githubusercontent.com/assets/17157560/13664905/0681b720-e6aa-11e5-9c76-5a74f1b06cc9.png)

**Comment by Alfro** [comment]
@agusave82  This is fixed thanks to the recent changes to the statistics module. Try it again.

**Comment by agusave82** [comment]
I returned to testing QA,

This bug is fixed.

Closing issue
