### ISSUE TITLE
9903 Pumukit 2.2.x: stadistics module: series: most viewed objects: enter a multimedia object: views

### ISSUE THREAD

**Issue by agusave82** [campusdomar/PuMuKIT2#95]
The steps are as follows:

1. go to the back-office
2. go to stats module
3. enter to multimedia objects
4. click on the player
5. Then, in the back-office refresh the page

Error:
The views is empty

![views](https://cloud.githubusercontent.com/assets/17157560/13665743/33e80256-e6ae-11e5-9b2b-16636178b286.png)

**Comment by Alfro** [comment]
@agusave82  Could you please check if it still happens? I can't reproduce it.

**Comment by agusave82** [comment]
@Alfro it continues to reproduced.

**Comment by Alfro** [comment]
@shermida Alright, this time for sure. Can you take another look at it?

**Comment by shermida** [comment]
Now it is solved.
