### ISSUE TITLE
Video Portal: it appears UCies

### ISSUE THREAD

**Issue by agusave82** [campusdomar/PuMuKIT2#96]
"UCies" appears in the browser bar 

![ucies](https://cloud.githubusercontent.com/assets/17157560/13667391/5911910c-e6b6-11e5-8665-7fd0eae0d863.png)

**Comment by agusave82** [comment]
@Alfro this error apperaed after updating the code to fix the bug # 84

**Comment by Alfro** [comment]
This is related to #88. It shouldn't appear after an installation from scratch

**Comment by agusave82** [comment]
closing issue, because it shouldn't appear after an installation from scratch
