### ISSUE TITLE
PuMuKIT 2.2.x: Media Manager: the multimedia series title are not showing

### ISSUE THREAD

**Issue by agusave82** [campusdomar/PuMuKIT2#97]
The multimedia series titles are not showing

![series_titles](https://cloud.githubusercontent.com/assets/17157560/13704312/83242cb2-e79b-11e5-87a3-f39dffbe570e.png)

**Comment by Alfro** [comment]
@agusave82  It's a problem with an older version of the example data. Reloading them should fix the issue.

**Comment by agusave82** [comment]
I returned to testing QA,

This bug is fixed.

Closing issue
