### ISSUE TITLE
Magic Urls: Broken functionality for the new basePlayer

### ISSUE THREAD

**Issue by Alfro** [campusdomar/PuMuKIT2#98]
After the changes to add a base player and give the option to either use JWPlayer or PaellaPlayer, the magic urls logic got broken. Since the WebTVBundle filter is applied to the players all the time, the video iframe throws a 404 even though the mmobj videoplayer page is correctly shown.

This affects the JWPlayer and PaellaPlayer

**Comment by Alfro** [comment]
Also, the series magic url are not working propertly either. Since it is related I may as well fix that with this.

**Comment by rubenrua** [comment]
We need tests for magic urls.
