### ISSUE TITLE
Error when searching on Opencast Importer

### ISSUE THREAD

**Issue by Alfro** [campusdomar/PuMuKIT2#99]
When trying to search a text with spaces the following error appears:
![saveus](https://cloud.githubusercontent.com/assets/11334172/14116248/0a197064-f5df-11e5-9366-ba74a56e242b.png)

**Comment by Alfro** [comment]
Fixed. @agusave82 Check if it still gives troubles.

**Comment by agusave82** [comment]
I returned to testing QA,

This bug is fixed.

Closing issue
